### ISSUE TITLE
Argument type error for function mie_S1_S2 and functions that calls it 

### ISSUE THREAD

**Issue by bchen112** [scottprahl/miepython#14]
Code
---------------------------------------------------
`miepython.mie_S1_S2(1.507-0.002j , 0.7086 , -1)`

Output
---------------------------------------------------
In [8]: miepython.mie_S1_S2(1.507-0.002j , 0.7086 , -1)

TypeError                                 Traceback (most recent call last)
<ipython-input-8-872f844d4264> in <module>
----> 1 miepython.mie_S1_S2(1.507-0.002j , 0.7086 , -1)

~/opt/anaconda3/envs/Bo_Chen_Research/lib/python3.8/site-packages/numba/core/dispatcher.py in _explain_matching_error(self, *args, **kws)
    654         msg = ("No matching definition for argument type(s) %s"
    655                % ', '.join(map(str, args)))
--> 656         raise TypeError(msg)
    657 
    658     def _search_new_conversions(self, *args, **kws):

TypeError: No matching definition for argument type(s) complex128, float64, int64

**Comment by bchen112** [comment]
I believe the issue has to do with jit. After deleting the jit modifier the i_par and mie_S1_S2 runs ok.

**Comment by scottprahl** [comment]
Thanks.  This is now fixed.  If you had written

    miepython.mie_S1_S2(1.507-0.002j , 0.7086 , [-1.0])

it probably would have worked.  Since this was unreasonable, I made it so that

    miepython.mie_S1_S2(1.507-0.002j , 0.7086 , -1)

works as it should now.  I will spin a new release soon if nothing else comes up.

**Comment by scottprahl** [comment]
fix is in release v2.1.0
