### ISSUE TITLE
Scattering phase matrix

### ISSUE THREAD

**Issue by nollety** [scottprahl/miepython#20]
Hi @scottprahl and thank you for a very useful Python package!

I noticed a method, `mie_S1_S2`, to compute the scattering amplitude functions, but no method to compute the scattering phase matrix (perhaps I miss it?) and I was wondering if this would be a feature that you'd be willing to have included in `miepython`?

In my application (radiative transfer for Earth observation), the knowledge of the scattering phase matrix lets one take polarisation into account, which is a significant improvement compared to unpolarised computations. But I don't know if this is something relevant for your application? From my understanding, deriving the scattering phase matrix from the scattering amplitude funtions is straightforward (e.g. with eqs. 5.2.105-6 in K. N. Liou (2002) - _An Introduction to Atmospheric Radiation, Second Edition_). If you are interested, I could prepare a pull request. :smiley:

**Comment by scottprahl** [comment]
@nollety A function to return a scattering matrix would be great --- it was on my todo list.  I would be happy to review and accept a pull request.  Ideally accompanied by a few tests.

**Comment by nollety** [comment]
Great, I'll be working on it then!

**Comment by scottprahl** [comment]
did you complete this by chance?

**Comment by scottprahl** [comment]
I see, you started a pull request.  I will close this issue now.

**Comment by nollety** [comment]
> did you complete this by chance?

Unfortunately no, I got stuck at the tests step ; I don't have reference scattering phase function data (with corresponding microphysical input parameters) that I could use for testing purposes.
This is still on my to do list but I have struggled to find time to allocate to that, hopefully I'll find the test data soon!
