### ISSUE TITLE
understanding the units of scattering amplitudes from mie_S1_S2()

### ISSUE THREAD

**Issue by davidmikolas** [scottprahl/miepython#3]
This seems very easy to use and I can _plot stuff_, but I'm not sure how to understand _and use_ the Scattering Amplitude outputs. With a plane wave intensity (W/m^2) on a single plarticle I'd like to know for example the scattered intensity at a given angle in W/sr). 

`help(miepython.mie_S1_S2)` returns 

>...The amplitude functions have been normalized so that when integrated over all 4pi solid angles, the integral will equal the single scattering albedo.  The units are weird, sr**(-0.5)

What exactly is the "single scattering albedo" is that the geometrical cross-section? I think I can understand the units (inverse radians) if this is assumed to be integrated over d phi (the azimuthal angle).

Is there a paper or source where I can read further? 

Thanks!

update: I've just seen https://github.com/scottprahl/miepython/blob/master/doc/03_angular_scattering.ipynb and will have a look now, and update further, but a published reference would be handy as well.

**Comment by davidmikolas** [comment]
Thanks for the speedy reply! 

I need to get to a library to try to access the link, and do it pretty quick because I currently live in Taiwan and Chinese New Year locks down (almost) everything that doesn't involve eating ;-) for at least a week.

I've asked a more specific question in Physics Stack Exchange: [Mie scattering amplitudes and intensities, trouble with units](https://physics.stackexchange.com/q/458041/83380) and I think that summarizes my question nicely.

**Comment by scottprahl** [comment]
Happy new year!

Good luck sorting this out. 

 I will mark this as closed because I think the answer is given in [Documentation on the Scattering Phase Function](https://github.com/scottprahl/miepython/blob/master/doc/03_angular_scattering.ipynb) that you have already found.

**Comment by davidmikolas** [comment]
Sounds good, I've made progress, and have raised another related issue. Let me know if you feel it's better as an extension of this or if it's okay to leave it separate from https://github.com/scottprahl/miepython/issues/3. 

Thanks!
