### ISSUE TITLE
How to get differential cross-sections that really scale with particle size (not normalized)?

### ISSUE THREAD

**Issue by davidmikolas** [scottprahl/miepython#5]
I'd like to calculate physical differential cross-sections from the normalized parameters and not sure how. **This would have units of area per unit solid angle.** https://en.wikipedia.org/wiki/Cross_section_(physics)#Differential_cross_section

I can square the amplitudes S₁ and S₂ and see that they give iper and ipar, but I still don't see how to recover actual differential cross-sections; they always integrate to 1.0 for any size particle (any reasonable x and m). 

It seems it all boils down to the following sentence in [03_angular_scattering.ipynb](https://github.com/scottprahl/miepython/blob/master/doc/03_angular_scattering.ipynb):

>Now if P₀ of light is scattered by a sphere then the scattered power on the detector will be...

I can imagine that P₀ might be the incident power over the geometrical cross-section πr² but I'm not sure if it's that, or it's related to one of the four values returned from `mp.mie()`. 

----

Example of what a differential cross-section plot with physical units would look like: See Figure 4.  http://plaza.ufl.edu/dwhahn/Rayleigh%20and%20Mie%20Light%20Scattering.pdf

![screen shot 2019-02-11 at 6 55 08 pm](https://user-images.githubusercontent.com/17236804/52558866-ab5ec980-2e2e-11e9-8cf2-8b387113bff1.png)

**Comment by scottprahl** [comment]
I added another section to [03_angular_scattering.ipynb](
https://github.com/scottprahl/miepython/blob/master/doc/03_angular_scattering.ipynb) providing an explanation and code for generating differential cross-sections.  Basically, you just multiply `miepython.i_unpolarized` by the geometric area and the extinction efficiency Q_ext

![image](https://user-images.githubusercontent.com/1901078/52584847-06b99900-2de8-11e9-9721-d5cebff06e28.png)

**Comment by davidmikolas** [comment]
Excellent! Bingo! Sweet! Problem solved, all good, etc.
